fund_of_working: '4080'
grinding_zone_percent: '0.05'
input_data_path: C:\Users\Korenyk.A\Documents\Проекты\design_of_mechanical_production\inputdata\initial_data.xlsx
kp: '1.45'
kv: '1.0'
passage_area: '10.0'
repair_zone_percent: '0.03'
report_path: C:\Users\Korenyk.A\Documents\Проекты\design_of_mechanical_production\output\report.txt
specific_areas:
  control_department: '0.05'
  equipment_warehouse: '0.2'
  sanitary_zone: '8.0'
  tool_storage: '0.3'
  work_piece_storage: '0.3'
workshop_nam: '3'
workshop_span: '12'
