fund_of_working: 4080
grinding_zone_percent: 0.05
kp: 1.45
kv: 1.0
passage_area: 10
repair_zone_percent: 0.025
specific_areas:
  control_department: 0.05
  equipment_warehouse: 0.2
  sanitary_zone: 8
  tool_storage: 0.3
  work_piece_storage: 0.3
