name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        echo "Start installing dependencies at $(date)"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "End installing dependencies at $(date)"

    - name: Install SQLite dependencies
      run: sudo apt-get install sqlite3

    - name: Check for machine_tools.db
      run: |
        python -c "import os, machine_tools; print(os.path.join(os.path.dirname(machine_tools.__file__), 'data', 'machine_tools.db'))"
        test -f $(python -c "import os, machine_tools; print(os.path.join(os.path.dirname(machine_tools.__file__), 'data', 'machine_tools.db'))")

    - name: Initialize database
      run: |
        python -c "from machine_tools import MachineToolsContainer; MachineToolsContainer().creator()"

    - name: Run tests
      run: |
        echo "Start pytest at $(date)"
        python -m pytest --timeout=120 tests/ --cov=design_of_mechanical_production --cov-report=xml
        echo "End pytest at $(date)"
