name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        echo "Start installing dependencies at $(date)"
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        echo "End installing dependencies at $(date)"

    - name: Run tests
      run: |
        echo "Start pytest at $(date)"
        python -m pytest --timeout=120 tests/ --cov=design_of_mechanical_production --cov-report=xml
        echo "End pytest at $(date)"
